/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MintRouteImport } from './routes/mint'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultUsernameRouteImport } from './routes/vault.$username'
import { Route as MomentsDemoRouteImport } from './routes/moments/demo'
import { Route as MomentsMomentIdRouteImport } from './routes/moments/$momentId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'
import { Route as ApiMomentsRouteImport } from './routes/api/moments'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiFriendRequestsRouteImport } from './routes/api/friend-requests'
import { Route as ApiCollectionsRouteImport } from './routes/api/collections'
import { Route as ApiFriendshipsFriendProfileIdRouteImport } from './routes/api/friendships/$friendProfileId'
import { Route as ApiFriendsSearchRouteImport } from './routes/api/friends/search'
import { Route as ApiFriendRequestsRequestIdRouteImport } from './routes/api/friend-requests/$requestId'
import { Route as ApiCollectionsCollectionIdRouteImport } from './routes/api/collections/$collectionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMomentsMomentIdReactionsRouteImport } from './routes/api/moments/$momentId/reactions'
import { Route as ApiMomentsMomentIdCommentsRouteImport } from './routes/api/moments/$momentId/comments'
import { Route as ApiMomentsMomentIdCollectionsRouteImport } from './routes/api/moments/$momentId/collections'
import { Route as ApiMomentsMomentIdAttendeesRouteImport } from './routes/api/moments/$momentId/attendees'
import { Route as ApiCollectionsCollectionIdMomentsRouteImport } from './routes/api/collections/$collectionId/moments'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultUsernameRoute = VaultUsernameRouteImport.update({
  id: '/vault/$username',
  path: '/vault/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsDemoRoute = MomentsDemoRouteImport.update({
  id: '/moments/demo',
  path: '/moments/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsMomentIdRoute = MomentsMomentIdRouteImport.update({
  id: '/moments/$momentId',
  path: '/moments/$momentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMomentsRoute = ApiMomentsRouteImport.update({
  id: '/api/moments',
  path: '/api/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFriendRequestsRoute = ApiFriendRequestsRouteImport.update({
  id: '/api/friend-requests',
  path: '/api/friend-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsRoute = ApiCollectionsRouteImport.update({
  id: '/api/collections',
  path: '/api/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFriendshipsFriendProfileIdRoute =
  ApiFriendshipsFriendProfileIdRouteImport.update({
    id: '/api/friendships/$friendProfileId',
    path: '/api/friendships/$friendProfileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFriendsSearchRoute = ApiFriendsSearchRouteImport.update({
  id: '/api/friends/search',
  path: '/api/friends/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFriendRequestsRequestIdRoute =
  ApiFriendRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => ApiFriendRequestsRoute,
  } as any)
const ApiCollectionsCollectionIdRoute =
  ApiCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => ApiCollectionsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMomentsMomentIdReactionsRoute =
  ApiMomentsMomentIdReactionsRouteImport.update({
    id: '/$momentId/reactions',
    path: '/$momentId/reactions',
    getParentRoute: () => ApiMomentsRoute,
  } as any)
const ApiMomentsMomentIdCommentsRoute =
  ApiMomentsMomentIdCommentsRouteImport.update({
    id: '/$momentId/comments',
    path: '/$momentId/comments',
    getParentRoute: () => ApiMomentsRoute,
  } as any)
const ApiMomentsMomentIdCollectionsRoute =
  ApiMomentsMomentIdCollectionsRouteImport.update({
    id: '/$momentId/collections',
    path: '/$momentId/collections',
    getParentRoute: () => ApiMomentsRoute,
  } as any)
const ApiMomentsMomentIdAttendeesRoute =
  ApiMomentsMomentIdAttendeesRouteImport.update({
    id: '/$momentId/attendees',
    path: '/$momentId/attendees',
    getParentRoute: () => ApiMomentsRoute,
  } as any)
const ApiCollectionsCollectionIdMomentsRoute =
  ApiCollectionsCollectionIdMomentsRouteImport.update({
    id: '/moments',
    path: '/moments',
    getParentRoute: () => ApiCollectionsCollectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/mint': typeof MintRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/friend-requests': typeof ApiFriendRequestsRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/moments/$momentId': typeof MomentsMomentIdRoute
  '/moments/demo': typeof MomentsDemoRoute
  '/vault/$username': typeof VaultUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/collections/$collectionId': typeof ApiCollectionsCollectionIdRouteWithChildren
  '/api/friend-requests/$requestId': typeof ApiFriendRequestsRequestIdRoute
  '/api/friends/search': typeof ApiFriendsSearchRoute
  '/api/friendships/$friendProfileId': typeof ApiFriendshipsFriendProfileIdRoute
  '/api/collections/$collectionId/moments': typeof ApiCollectionsCollectionIdMomentsRoute
  '/api/moments/$momentId/attendees': typeof ApiMomentsMomentIdAttendeesRoute
  '/api/moments/$momentId/collections': typeof ApiMomentsMomentIdCollectionsRoute
  '/api/moments/$momentId/comments': typeof ApiMomentsMomentIdCommentsRoute
  '/api/moments/$momentId/reactions': typeof ApiMomentsMomentIdReactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/mint': typeof MintRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/friend-requests': typeof ApiFriendRequestsRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/moments/$momentId': typeof MomentsMomentIdRoute
  '/moments/demo': typeof MomentsDemoRoute
  '/vault/$username': typeof VaultUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/collections/$collectionId': typeof ApiCollectionsCollectionIdRouteWithChildren
  '/api/friend-requests/$requestId': typeof ApiFriendRequestsRequestIdRoute
  '/api/friends/search': typeof ApiFriendsSearchRoute
  '/api/friendships/$friendProfileId': typeof ApiFriendshipsFriendProfileIdRoute
  '/api/collections/$collectionId/moments': typeof ApiCollectionsCollectionIdMomentsRoute
  '/api/moments/$momentId/attendees': typeof ApiMomentsMomentIdAttendeesRoute
  '/api/moments/$momentId/collections': typeof ApiMomentsMomentIdCollectionsRoute
  '/api/moments/$momentId/comments': typeof ApiMomentsMomentIdCommentsRoute
  '/api/moments/$momentId/reactions': typeof ApiMomentsMomentIdReactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/mint': typeof MintRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/friend-requests': typeof ApiFriendRequestsRouteWithChildren
  '/api/media': typeof ApiMediaRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/moments/$momentId': typeof MomentsMomentIdRoute
  '/moments/demo': typeof MomentsDemoRoute
  '/vault/$username': typeof VaultUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/collections/$collectionId': typeof ApiCollectionsCollectionIdRouteWithChildren
  '/api/friend-requests/$requestId': typeof ApiFriendRequestsRequestIdRoute
  '/api/friends/search': typeof ApiFriendsSearchRoute
  '/api/friendships/$friendProfileId': typeof ApiFriendshipsFriendProfileIdRoute
  '/api/collections/$collectionId/moments': typeof ApiCollectionsCollectionIdMomentsRoute
  '/api/moments/$momentId/attendees': typeof ApiMomentsMomentIdAttendeesRoute
  '/api/moments/$momentId/collections': typeof ApiMomentsMomentIdCollectionsRoute
  '/api/moments/$momentId/comments': typeof ApiMomentsMomentIdCommentsRoute
  '/api/moments/$momentId/reactions': typeof ApiMomentsMomentIdReactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/friends'
    | '/mint'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/api/collections'
    | '/api/friend-requests'
    | '/api/media'
    | '/api/moments'
    | '/collections/$collectionId'
    | '/moments/$momentId'
    | '/moments/demo'
    | '/vault/$username'
    | '/api/auth/$'
    | '/api/collections/$collectionId'
    | '/api/friend-requests/$requestId'
    | '/api/friends/search'
    | '/api/friendships/$friendProfileId'
    | '/api/collections/$collectionId/moments'
    | '/api/moments/$momentId/attendees'
    | '/api/moments/$momentId/collections'
    | '/api/moments/$momentId/comments'
    | '/api/moments/$momentId/reactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/friends'
    | '/mint'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/api/collections'
    | '/api/friend-requests'
    | '/api/media'
    | '/api/moments'
    | '/collections/$collectionId'
    | '/moments/$momentId'
    | '/moments/demo'
    | '/vault/$username'
    | '/api/auth/$'
    | '/api/collections/$collectionId'
    | '/api/friend-requests/$requestId'
    | '/api/friends/search'
    | '/api/friendships/$friendProfileId'
    | '/api/collections/$collectionId/moments'
    | '/api/moments/$momentId/attendees'
    | '/api/moments/$momentId/collections'
    | '/api/moments/$momentId/comments'
    | '/api/moments/$momentId/reactions'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/friends'
    | '/mint'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/api/collections'
    | '/api/friend-requests'
    | '/api/media'
    | '/api/moments'
    | '/collections/$collectionId'
    | '/moments/$momentId'
    | '/moments/demo'
    | '/vault/$username'
    | '/api/auth/$'
    | '/api/collections/$collectionId'
    | '/api/friend-requests/$requestId'
    | '/api/friends/search'
    | '/api/friendships/$friendProfileId'
    | '/api/collections/$collectionId/moments'
    | '/api/moments/$momentId/attendees'
    | '/api/moments/$momentId/collections'
    | '/api/moments/$momentId/comments'
    | '/api/moments/$momentId/reactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  FriendsRoute: typeof FriendsRoute
  MintRoute: typeof MintRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiCollectionsRoute: typeof ApiCollectionsRouteWithChildren
  ApiFriendRequestsRoute: typeof ApiFriendRequestsRouteWithChildren
  ApiMediaRoute: typeof ApiMediaRoute
  ApiMomentsRoute: typeof ApiMomentsRouteWithChildren
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  MomentsMomentIdRoute: typeof MomentsMomentIdRoute
  MomentsDemoRoute: typeof MomentsDemoRoute
  VaultUsernameRoute: typeof VaultUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFriendsSearchRoute: typeof ApiFriendsSearchRoute
  ApiFriendshipsFriendProfileIdRoute: typeof ApiFriendshipsFriendProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$username': {
      id: '/vault/$username'
      path: '/vault/$username'
      fullPath: '/vault/$username'
      preLoaderRoute: typeof VaultUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments/demo': {
      id: '/moments/demo'
      path: '/moments/demo'
      fullPath: '/moments/demo'
      preLoaderRoute: typeof MomentsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments/$momentId': {
      id: '/moments/$momentId'
      path: '/moments/$momentId'
      fullPath: '/moments/$momentId'
      preLoaderRoute: typeof MomentsMomentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moments': {
      id: '/api/moments'
      path: '/api/moments'
      fullPath: '/api/moments'
      preLoaderRoute: typeof ApiMomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friend-requests': {
      id: '/api/friend-requests'
      path: '/api/friend-requests'
      fullPath: '/api/friend-requests'
      preLoaderRoute: typeof ApiFriendRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections': {
      id: '/api/collections'
      path: '/api/collections'
      fullPath: '/api/collections'
      preLoaderRoute: typeof ApiCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friendships/$friendProfileId': {
      id: '/api/friendships/$friendProfileId'
      path: '/api/friendships/$friendProfileId'
      fullPath: '/api/friendships/$friendProfileId'
      preLoaderRoute: typeof ApiFriendshipsFriendProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friends/search': {
      id: '/api/friends/search'
      path: '/api/friends/search'
      fullPath: '/api/friends/search'
      preLoaderRoute: typeof ApiFriendsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friend-requests/$requestId': {
      id: '/api/friend-requests/$requestId'
      path: '/$requestId'
      fullPath: '/api/friend-requests/$requestId'
      preLoaderRoute: typeof ApiFriendRequestsRequestIdRouteImport
      parentRoute: typeof ApiFriendRequestsRoute
    }
    '/api/collections/$collectionId': {
      id: '/api/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/api/collections/$collectionId'
      preLoaderRoute: typeof ApiCollectionsCollectionIdRouteImport
      parentRoute: typeof ApiCollectionsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moments/$momentId/reactions': {
      id: '/api/moments/$momentId/reactions'
      path: '/$momentId/reactions'
      fullPath: '/api/moments/$momentId/reactions'
      preLoaderRoute: typeof ApiMomentsMomentIdReactionsRouteImport
      parentRoute: typeof ApiMomentsRoute
    }
    '/api/moments/$momentId/comments': {
      id: '/api/moments/$momentId/comments'
      path: '/$momentId/comments'
      fullPath: '/api/moments/$momentId/comments'
      preLoaderRoute: typeof ApiMomentsMomentIdCommentsRouteImport
      parentRoute: typeof ApiMomentsRoute
    }
    '/api/moments/$momentId/collections': {
      id: '/api/moments/$momentId/collections'
      path: '/$momentId/collections'
      fullPath: '/api/moments/$momentId/collections'
      preLoaderRoute: typeof ApiMomentsMomentIdCollectionsRouteImport
      parentRoute: typeof ApiMomentsRoute
    }
    '/api/moments/$momentId/attendees': {
      id: '/api/moments/$momentId/attendees'
      path: '/$momentId/attendees'
      fullPath: '/api/moments/$momentId/attendees'
      preLoaderRoute: typeof ApiMomentsMomentIdAttendeesRouteImport
      parentRoute: typeof ApiMomentsRoute
    }
    '/api/collections/$collectionId/moments': {
      id: '/api/collections/$collectionId/moments'
      path: '/moments'
      fullPath: '/api/collections/$collectionId/moments'
      preLoaderRoute: typeof ApiCollectionsCollectionIdMomentsRouteImport
      parentRoute: typeof ApiCollectionsCollectionIdRoute
    }
  }
}

interface ApiCollectionsCollectionIdRouteChildren {
  ApiCollectionsCollectionIdMomentsRoute: typeof ApiCollectionsCollectionIdMomentsRoute
}

const ApiCollectionsCollectionIdRouteChildren: ApiCollectionsCollectionIdRouteChildren =
  {
    ApiCollectionsCollectionIdMomentsRoute:
      ApiCollectionsCollectionIdMomentsRoute,
  }

const ApiCollectionsCollectionIdRouteWithChildren =
  ApiCollectionsCollectionIdRoute._addFileChildren(
    ApiCollectionsCollectionIdRouteChildren,
  )

interface ApiCollectionsRouteChildren {
  ApiCollectionsCollectionIdRoute: typeof ApiCollectionsCollectionIdRouteWithChildren
}

const ApiCollectionsRouteChildren: ApiCollectionsRouteChildren = {
  ApiCollectionsCollectionIdRoute: ApiCollectionsCollectionIdRouteWithChildren,
}

const ApiCollectionsRouteWithChildren = ApiCollectionsRoute._addFileChildren(
  ApiCollectionsRouteChildren,
)

interface ApiFriendRequestsRouteChildren {
  ApiFriendRequestsRequestIdRoute: typeof ApiFriendRequestsRequestIdRoute
}

const ApiFriendRequestsRouteChildren: ApiFriendRequestsRouteChildren = {
  ApiFriendRequestsRequestIdRoute: ApiFriendRequestsRequestIdRoute,
}

const ApiFriendRequestsRouteWithChildren =
  ApiFriendRequestsRoute._addFileChildren(ApiFriendRequestsRouteChildren)

interface ApiMomentsRouteChildren {
  ApiMomentsMomentIdAttendeesRoute: typeof ApiMomentsMomentIdAttendeesRoute
  ApiMomentsMomentIdCollectionsRoute: typeof ApiMomentsMomentIdCollectionsRoute
  ApiMomentsMomentIdCommentsRoute: typeof ApiMomentsMomentIdCommentsRoute
  ApiMomentsMomentIdReactionsRoute: typeof ApiMomentsMomentIdReactionsRoute
}

const ApiMomentsRouteChildren: ApiMomentsRouteChildren = {
  ApiMomentsMomentIdAttendeesRoute: ApiMomentsMomentIdAttendeesRoute,
  ApiMomentsMomentIdCollectionsRoute: ApiMomentsMomentIdCollectionsRoute,
  ApiMomentsMomentIdCommentsRoute: ApiMomentsMomentIdCommentsRoute,
  ApiMomentsMomentIdReactionsRoute: ApiMomentsMomentIdReactionsRoute,
}

const ApiMomentsRouteWithChildren = ApiMomentsRoute._addFileChildren(
  ApiMomentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  FriendsRoute: FriendsRoute,
  MintRoute: MintRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiCollectionsRoute: ApiCollectionsRouteWithChildren,
  ApiFriendRequestsRoute: ApiFriendRequestsRouteWithChildren,
  ApiMediaRoute: ApiMediaRoute,
  ApiMomentsRoute: ApiMomentsRouteWithChildren,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  MomentsMomentIdRoute: MomentsMomentIdRoute,
  MomentsDemoRoute: MomentsDemoRoute,
  VaultUsernameRoute: VaultUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFriendsSearchRoute: ApiFriendsSearchRoute,
  ApiFriendshipsFriendProfileIdRoute: ApiFriendshipsFriendProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
